version: "3.8"
networks:
    yofin-box:
        driver: bridge
services:
    app:
        build:
            context: ./
            dockerfile: ./_docker/app/Dockerfile
        image: yofin-box-app
        tty: true
        container_name: yofin-box-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./_docker/app/php.ini:/usr/local/etc/php/php.ini
            - ./:/var/www

        networks:
            - yofin-box

    node:
        build:
            context: .
            dockerfile: ./_docker/nodejs/Dockerfile
        tty: true
        ports:
            - "5173:5173"
        working_dir: /var/www
        volumes:
            - ./:/var/www

    db:
        image: postgres
        container_name: yofin-box-db
        restart: unless-stopped
        environment:
            PGDATA: /var/lib/postgresql/data
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - ${DOCKER_DB_PORT}:5432
        networks:
            - yofin-box

    nginx:
        image: nginx:1.17-alpine
        container_name: yofin-box-nginx
        restart: unless-stopped
        ports:
            - ${NGINX_PORT}:80
        volumes:
            - ./:/var/www
            - ./_docker/nginx:/etc/nginx/conf.d
        networks:
            - yofin-box

    redis:
        image: redis:alpine
        container_name: yofin-box-redis
        restart: unless-stopped
        ports:
            - ${DOCKER_REDIS_PORT}:6379
        networks:
            - yofin-box

    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        logging:
            driver: 'none'
        ports:
            - 1025:1025
            - 8025:8025
        networks:
            - yofin-box

    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: phpmyadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_PORT: ${DB_PORT}
        depends_on:
            - db
        ports:
            - 8888:80
        networks:
            - yofin-box
